language: python
python:
  - "3.9"

before_install:
  - mv travis_secrets.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install sqlalchemy

script:
  - hass -c . --script check_config --info all

notifications:
  email:
    on_success: never
    on_failure: always
