homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Africa/Johannesburg
  currency: ZAR
  internal_url: "http://hassio.wiersma.iot:8123"
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enabled all default things
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Enables the energy dashboard
energy:

hassio:

http:
  cors_allowed_origins:
    - "http://localhost:8080"

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Purge database interval
recorder:
  purge_keep_days: 14

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate

# Mobile App
mobile_app:

# Cloud
cloud:

# System health
system_health:

# Includes =================================

group: !include groups.yaml
script: !include scripts.yaml
