esphome:
  name: geyser-temperature-monitor
  friendly_name: "Geyser Temperature Monitor"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  level: "DEBUG"

api:
  id: api_id

ota:
  - platform: esphome

http_request:

wifi:

esp32_improv:
  authorizer: none

number:
  - platform: template
    name: "Temperature Minimum"
    id: geyser_temp_min
    icon: mdi:thermometer-chevron-down
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 20
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "°C"
  - platform: template
    name: "Temperature Maximum"
    id: geyser_temp_max
    icon: mdi:thermometer-chevron-up
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 60
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "°C"
  - platform: template
    name: "Temperature Offset"
    id: temp_offset
    icon: mdi:thermometer-plus
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 1.2
    min_value: -10
    max_value: 10
    step: 0.1
    unit_of_measurement: "°C"

sensor:
  - platform: adc
    pin: GPIO36
    id: geyser_adc_raw
    attenuation: 12db
    update_interval: 5s
    internal: true
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 5
  - platform: resistance
    id: geyser_ntc_resistance
    sensor: geyser_adc_raw
    configuration: DOWNSTREAM
    resistor: 10kΩ

  - platform: ntc
    sensor: geyser_ntc_resistance
    name: "Geyser Temperature"
    id: geyser_temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    calibration:
      b_constant: 3455
      reference_temperature: 25°C
      reference_resistance: 10000ohm
    filters:
      - lambda: |-
          float offset = id(temp_offset).state;
          return x + offset;

  - platform: template
    name: "Geyser Hot Water Percentage"
    id: geyser_hot_water_percentage
    icon: "mdi:percent"
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      // percentage = depth(m) / tank_depth(m) * 100
      float temp = id(geyser_temperature).state;
      float min = id(geyser_temp_min).state;
      float max = id(geyser_temp_max).state;
      return (temp - min) / (max - min) * 100;