# Doors
binary_sensor:
  - platform: mqtt
    name: "Verandah Door"
    state_topic: "tele/rf/RESULT"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "94A50A"
    payload_off: "94A50E"
    device_class: door
  - platform: mqtt
    name: "Front Door"
    state_topic: "tele/rf/RESULT"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "92550A"
    payload_off: "92550E"
    device_class: door
  - platform: mqtt
    name: "Kitchen Door"
    state_topic: "tele/rf/RESULT"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "941B0A"
    payload_off: "941B0E"
    device_class: door
  - platform: mqtt
    name: "Garage Door Right"
    state_topic: "tele/rf/RESULT"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "010101"
    payload_off: "010102"
    device_class: door
  - platform: mqtt
    name: "Garage Door Left"
    state_topic: "tele/rf/RESULT"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "010103"
    payload_off: "010104"
    device_class: door

# Garage Doors
cover:
  - platform: mqtt
    name: "Garage Door Right Test"
    state_topic: "cmnd/garage_right_sensor/POWER2"
    command_topic: "cmnd/garage_right/POWER"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "ON"
    state_closed: "OFF"
    optimistic: false
    retain: false
    device_class: garage
