---
sensor:
  - platform: influxdb
    api_version: 2
    ssl: true
    verify_ssl: false
    host: influx.wiersma.lan
    port: 443
    token: !secret influxdb_api_key
    organization: 2912765fac33d7d4
    bucket: iotawatt
    queries_flux:
      - name: "plugs1_wh"
        unique_id: "iotawatt_plugs1_wh"
        range_start: "today()"
        query: >
            filter(fn: (r) => r["_measurement"] == "plugs1.wh")
            |> cumulativeSum()
        group_function: last
      - name: "plugs2_wh"
        unique_id: "iotawatt_plugs2_wh"
        range_start: "today()"
        query: >
          filter(fn: (r) => r["_measurement"] == "plugs2.wh")
          |> cumulativeSum()
        group_function: last

homeassistant:
  customize_glob:
    "sensor.*_wh":
      icon: mdi:lightning-bolt
      device_class: energy
      last_reset: "{{ (now().replace(hour=0, minute=0, second=0, microsecond=0)) }}"
      state_class: measurement
      unit_of_measurement: Wh
