# Lights
light:
  # Kitchen Switch
  - platform: mqtt
    name: "Night"
    state_topic: "stat/kitchen/POWER1"
    command_topic: "cmnd/kitchen/POWER1"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Dining Room"
    state_topic: "stat/kitchen/POWER2"
    command_topic: "cmnd/kitchen/POWER2"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Kitchen"
    state_topic: "stat/kitchen/POWER3"
    command_topic: "cmnd/kitchen/POWER3"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Lounge Switch
  - platform: mqtt
    name: "Lounge"
    state_topic: "stat/lounge/POWER"
    command_topic: "cmnd/lounge/POWER"
    availability_topic: "tele/lounge/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Study Switch
  - platform: mqtt
    name: "Study"
    state_topic: "stat/study/POWER"
    command_topic: "cmnd/study/POWER"
    availability_topic: "tele/study/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Bedroom Switch
  - platform: mqtt
    name: "Bedroom"
    state_topic: "stat/bedroom/POWER1"
    command_topic: "cmnd/bedroom/POWER1"
    availability_topic: "tele/bedroom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Ensuite"
    state_topic: "stat/bedroom/POWER2"
    command_topic: "cmnd/bedroom/POWER2"
    availability_topic: "tele/bedroom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

# Automation ===============================

automation:
  - alias: "Arrival Mode"
        trigger:
          - platform: state
            entity_id: group.all_devices
            to: "home"
        condition:
          - condition: time
            after: "16:00:00"
            before: "23:00:00"
        action:
            service: light.turn_on
            entity_id: light.night

  - alias: "Away Mode"
        trigger:
            platform: state
            entity_id: group.all_devices
            to: "not_home"
        action:
            service: light.turn_off
            entity_id: group.all_lights
