mqtt:
  # Lights
  light:
    # Outside Switch
    - unique_id: "mqtt.light.outside"
      name: "Outside"
      state_topic: "stat/outside/POWER"
      command_topic: "cmnd/outside/POWER"
      availability_topic: "tele/outside/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false


    # Entrance Switch
    - unique_id: "mqtt.light.entrance"
      name: "Entrance"
      state_topic: "stat/entrance/POWER"
      command_topic: "cmnd/entrance/POWER"
      availability_topic: "tele/entrance/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

    # Hallway Switch
    - unique_id: "mqtt.light.hallway"
      name: "Hallway"
      state_topic: "stat/hallway/POWER"
      command_topic: "cmnd/hallway/POWER"
      availability_topic: "tele/hallway/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

    # Breezeway Switch
    - unique_id: "mqtt.light.breezeway"
      name: "Breezeway"
      state_topic: "stat/breezeway/POWER"
      command_topic: "cmnd/breezeway/POWER"
      availability_topic: "tele/breezeway/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

    # Bathroom Switch
    - unique_id: "mqtt.light.bathroom"
      name: "Bathroom"
      state_topic: "stat/bathroom/POWER"
      command_topic: "cmnd/bathroom/POWER"
      availability_topic: "tele/bathroom/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

    # Toilet Switch
    - unique_id: "mqtt.light.toilet"
      name: "Toilet"
      state_topic: "stat/toilet/POWER"
      command_topic: "cmnd/toilet/POWER"
      availability_topic: "tele/toilet/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

    # Driveway Switch
    - unique_id: "mqtt.light.driveway"
      name: "Driveway"
      state_topic: "stat/driveway/POWER"
      command_topic: "cmnd/driveway/POWER"
      availability_topic: "tele/driveway/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false

# Automation ===============================

automation:
  - alias: Sync Tasmota states
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      service: mqtt.publish
      data:
        topic: cmnd/tasmotas/POWER0
        payload: ''

  - alias: Arrival Mode
    trigger:
      - platform: state
        entity_id: group.everyone
        from: "not_home"
        to: "home"
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
    action:
        service: light.turn_on
        entity_id: light.entrance

  - alias: Away Mode
    trigger:
        platform: state
        entity_id: group.everyone
        from: "home"
        to: "not_home"
        for:
          minutes: 5
    action:
        service: light.turn_off
        data_template:
            entity_id: >-
                {% set state = 'on' %}
                {% set filter = ['light.driveway'] %}
                {% set names = states.light
                | selectattr('state','eq', state)
                | rejectattr('entity_id','in', filter)
                | map(attribute = 'entity_id')
                | join(',')
                %}
                {% if names.count('.') >= 1 %}
                {{ names }}
                {% else %}
                light.dummy
                {% endif %}
