# Lights
light:
  # Kitchen Switch
  - platform: mqtt
    name: "Night"
    state_topic: "stat/kitchen/POWER1"
    command_topic: "cmnd/kitchen/POWER1"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Dining Room"
    state_topic: "stat/kitchen/POWER2"
    command_topic: "cmnd/kitchen/POWER2"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Kitchen"
    state_topic: "stat/kitchen/POWER3"
    command_topic: "cmnd/kitchen/POWER3"
    availability_topic: "tele/kitchen/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  # Bar Switch
  - platform: mqtt
    name: "Bar"
    state_topic: "stat/bar/POWER"
    command_topic: "cmnd/bar/POWER"
    availability_topic: "tele/bar/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Bar Lamp
  - platform: mqtt
    name: "Bar Lamp"
    state_topic: "stat/bar-lamp/POWER"
    command_topic: "cmnd/bar-lamp/POWER"
    availability_topic: "tele/bar-lamp/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Lounge Lamps
  - platform: group
    name: "Bar Lights"
    entities:
      - light.bar_lamp
      - light.bar

  # Lounge Switch
  - platform: mqtt
    name: "Lounge Main"
    state_topic: "stat/lounge/POWER"
    command_topic: "cmnd/lounge/POWER"
    availability_topic: "tele/lounge/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Lounge Lamp 1
  - platform: mqtt
    name: "Lounge Lamp 1"
    state_topic: "stat/lounge-lamp-1/POWER"
    command_topic: "cmnd/lounge-lamp-1/POWER"
    availability_topic: "tele/lounge-lamp-1/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Lounge Lamp 2
  - platform: mqtt
    name: "Lounge Lamp 2"
    state_topic: "stat/lounge-lamp-2/POWER"
    command_topic: "cmnd/lounge-lamp-2/POWER"
    availability_topic: "tele/lounge-lamp-2/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  # Lounge Lamps
  - platform: group
    name: "Lounge Lamps"
    entities:
      - light.lounge_lamp_1
      - light.lounge_lamp_2

  # Verandah Switch
  - platform: mqtt
    name: "Verandah"
    state_topic: "stat/verandah/POWER1"
    command_topic: "cmnd/verandah/POWER1"
    availability_topic: "tele/verandah/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  # Study Switch
  - platform: mqtt
    name: "Study"
    state_topic: "stat/study/POWER"
    command_topic: "cmnd/study/POWER"
    availability_topic: "tele/study/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  # Bedroom Switch
  - platform: mqtt
    name: "Bedroom"
    state_topic: "stat/bedroom/POWER1"
    command_topic: "cmnd/bedroom/POWER1"
    availability_topic: "tele/bedroom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Ensuite"
    state_topic: "stat/bedroom/POWER2"
    command_topic: "cmnd/bedroom/POWER2"
    availability_topic: "tele/bedroom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  # Entrace Switch
  - platform: mqtt
    name: "Entrance"
    state_topic: "stat/entrance/POWER1"
    command_topic: "cmnd/entrance/POWER1"
    availability_topic: "tele/entrance/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

# Automation ===============================

automation:
  - alias: Lounge Lamps Toggle
    trigger:
        platform: mqtt
        topic: "cmnd/lounge-lamps/POWER"
        payload: 'TOGGLE'
    action:
        service: light.toggle
        entity_id: light.lounge_lamps
  - alias: Bar Lamps Toggle
    trigger:
        platform: mqtt
        topic: "cmnd/bar-lamps/POWER"
        payload: 'TOGGLE'
    action:
        service: light.toggle
        entity_id: light.bar_lights

  - alias: Arrival Mode
    trigger:
      - platform: state
        entity_id: group.everyone
        to: "home"
    condition:
      - condition: time
        after: "18:00:00"
        before: "23:00:00"
    action:
        service: light.turn_on
        entity_id: light.entrance

  - alias: Away Mode
    trigger:
        platform: state
        entity_id: group.everyone
        to: "not_home"
    action:
        service: light.turn_off
        entity_id: all
