sensor:
  # Reservoir Smoothing
  - platform: filter
    unique_id: filter.sensor.reservoir_pressure_smoothed
    name: Pressure Smoothed
    entity_id: sensor.reservoir_pressure
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: time_simple_moving_average
        window_size: 00:05
  # Geyser Smoothing
  - platform: filter
    unique_id: filter.sensor.geyser_temperature_smoothed
    name: Temperature Smoothed
    entity_id: sensor.geyser_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: time_simple_moving_average
        window_size: 00:05
