mqtt:
  # Smoke Detector
  binary_sensor:
    - name: "Smoke Detector"
      state_topic: "tele/rf/RESULT"
      value_template: "{{ value_json.RfReceived.Data }}"
      payload_on: "A63166"
      off_delay: 1800
      device_class: smoke

# Automation ===============================

automation:
  - alias: Fire Fire Fire
    trigger:
        platform: state
        entity_id: binary_sensor.smoke_detector
        to: 'on'
    action:
        service: light.turn_on
        entity_id: all
